apiVersion: v1
kind: Secret
metadata:
 name: mysql-secret
 namespace: petrescue-ns
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: petrescue_db
  MYSQL_USER: petrescue_user
  MYSQL_PASSWORD: petrescue_pass
